version: '3.8'

services:
  postgres:
    container_name: db.henryjperez
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    depends_on:
      - postgres
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 5050:80

  app_dev:
    container_name: app_dev
    profiles:
      - app_dev # docker compose --profile app_dev up
    env_file:
      - .env
    depends_on:
      - pgadmin
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - type: bind
        source: ./src
        target: /usr/app/src
    build:
      context: ./
      dockerfile: dockerfile.dev

  app:
    container_name: app
    profiles:
      - app # docker compose --profile app up
    env_file:
      - .env
    depends_on:
      - pgadmin
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/usr/app/src
    build:
      context: ./
      dockerfile: dockerfile