version: '3.8'

services:
  postgres:
    container_name: db.henryjperez
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    depends_on:
      - postgres
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 5050:80

  # app:
  #   container_name: app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - pgadmin
  #   ports:
  #     - "${PORT}:9000"
  #   volumes:
  #     - .:/usr/app
  #   build:
  #     context: ./
  #     target: dev
  #   command: yarn dev