# Extent the "Query" and "Mutation" types for adding the things you have in the this file
extend type Query {
	test: Test
}
extend type Mutation {
	setTest(value: String): String
}

type Test {
	ping: String
	pong: String
}