# Extent the "Query" and "Mutation" types for adding the things you have in the this file
extend type Query {
	moreTests: Test
}
extend type Mutation {
	setMoreTests(value: String): String
}

type Test {
	name: String
	value: Int
}